### ISSUE TITLE
Error during compilation of LCE converter

### ISSUE THREAD

**Issue by lkindrat-xmos** [larq/compute-engine#411] opened 2020-06-25 21:22 UTC
I have been trying to build the LCE converter as described in https://docs.larq.dev/compute-engine/build/ and got the following error when running `bazel build :build_pip_pkg` in the docker container:
```
ERROR: /root/.cache/bazel/_bazel_root/aa829f8eaa4f35b2fc6d736b3640d755/external/org_tensorflow/tensorflow/core/kernels/BUILD:357:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:extract_image_patches_op' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/aa829f8eaa4f35b2fc6d736b3640d755/execroot/larq_compute_engine && \
  exec env - \
    ANDROID_BUILD_TOOLS_VERSION=28.0.3 \
    ANDROID_NDK_API_LEVEL=21 \
    ANDROID_NDK_HOME=/tmp/lce_android/ndk/18.1.5063045 \
    ANDROID_SDK_API_LEVEL=29 \
    ANDROID_SDK_HOME=/tmp/lce_android \
    PATH=/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.1/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/kernels/_objs/extract_image_patches_op/extract_image_patches_op.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/kernels/_objs/extract_image_patches_op/extract_image_patches_op.pic.o' -DTENSORFLOW_USE_CUSTOM_CONTRACTION_KERNEL -DTENSORFLOW_USE_MKLDNN_CONTRACTION_KERNEL -DTF_USE_SNAPPY -DEIGEN_MPL2_ONLY '-DEIGEN_MAX_ALIGN_BYTES=64' '-DEIGEN_HAS_TYPE_TRAITS=0' -DHAVE_SYS_UIO_H -D__CLANG_SUPPORT_DYN_ANNOTATION__ -iquote external/org_tensorflow -iquote bazel-out/k8-opt/bin/external/org_tensorflow -iquote external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/k8-opt/bin/external/local_config_sycl -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/mkl_dnn -iquote bazel-out/k8-opt/bin/external/mkl_dnn -iquote external/nsync -iquote bazel-out/k8-opt/bin/external/nsync -iquote external/gif -iquote bazel-out/k8-opt/bin/external/gif -iquote external/libjpeg_turbo -iquote bazel-out/k8-opt/bin/external/libjpeg_turbo -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/k8-opt/bin/external/zlib -iquote external/com_googlesource_code_re2 -iquote bazel-out/k8-opt/bin/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/k8-opt/bin/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/k8-opt/bin/external/fft2d -iquote external/highwayhash -iquote bazel-out/k8-opt/bin/external/highwayhash -iquote external/double_conversion -iquote bazel-out/k8-opt/bin/external/double_conversion -iquote external/snappy -iquote bazel-out/k8-opt/bin/external/snappy -isystem external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/mkl_dnn/include -isystem bazel-out/k8-opt/bin/external/mkl_dnn/include -isystem external/mkl_dnn/src -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src -isystem external/mkl_dnn/src/common -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/common -isystem external/mkl_dnn/src/cpu -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/cpu -isystem external/mkl_dnn/src/cpu/gemm -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/cpu/gemm -isystem external/mkl_dnn/src/cpu/xbyak -isystem bazel-out/k8-opt/bin/external/mkl_dnn/src/cpu/xbyak -isystem external/nsync/public -isystem bazel-out/k8-opt/bin/external/nsync/public -isystem external/gif -isystem bazel-out/k8-opt/bin/external/gif -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/k8-opt/bin/external/zlib -isystem external/farmhash_archive/src -isystem bazel-out/k8-opt/bin/external/farmhash_archive/src -isystem external/double_conversion -isystem bazel-out/k8-opt/bin/external/double_conversion '-std=c++11' -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -DTFLITE_WITH_RUY '-std=c++14' -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare '-ftemplate-depth=900' -fno-exceptions -msse3 -DTENSORFLOW_MONOLITHIC_BUILD -pthread -c external/org_tensorflow/tensorflow/core/kernels/extract_image_patches_op.cc -o bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/core/kernels/_objs/extract_image_patches_op/extract_image_patches_op.pic.o)
Execution platform: @local_execution_config_platform//:platform
In file included from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:117:0,
                 from external/org_tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from external/org_tensorflow/tensorflow/core/kernels/extract_image_patches_op.h:19,
                 from external/org_tensorflow/tensorflow/core/kernels/extract_image_patches_op.cc:21:
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorImagePatch.h: In static member function 'static void Eigen::internal::EvalRange<Evaluator, StorageIndex, true>::run(Evaluator*, StorageIndex, StorageIndex) [with Evaluator = Eigen::TensorEvaluator<const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 4, 1, int>, 16, Eigen::MakePointer>, const Eigen::TensorReshapingOp<const Eigen::DSizes<int, 4>, const Eigen::TensorImagePatchOp<-1, -1, const Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 4, 1, int>, 16, Eigen::MakePointer> > > >, Eigen::ThreadPoolDevice>; StorageIndex = int]':
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorImagePatch.h:546:7: internal compiler error: in emit_move_insn, at expr.c:3698
       values[i] = coeff(index+i);
       ^~~~~~
0x903daf emit_move_insn(rtx_def*, rtx_def*)
	/dt7-src/gcc/expr.c:3697
0x8f3f06 store_bit_field_1
	/dt7-src/gcc/expmed.c:814
0x8f451c store_bit_field(rtx_def*, unsigned long, unsigned long, unsigned long, unsigned long, machine_mode, rtx_def*, bool)
	/dt7-src/gcc/expmed.c:1122
0x90eb4a store_field
	/dt7-src/gcc/expr.c:6976
0x90c300 expand_assignment(tree_node*, tree_node*, bool)
	/dt7-src/gcc/expr.c:5212
0x81aaea expand_call_stmt
	/dt7-src/gcc/cfgexpand.c:2656
0x81aaea expand_gimple_stmt_1
	/dt7-src/gcc/cfgexpand.c:3571
0x81aaea expand_gimple_stmt
	/dt7-src/gcc/cfgexpand.c:3737
0x81c500 expand_gimple_basic_block
	/dt7-src/gcc/cfgexpand.c:5744
0x8211d6 execute
	/dt7-src/gcc/cfgexpand.c:6357
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
Target //:build_pip_pkg failed to build
INFO: Elapsed time: 769.753s, Critical Path: 96.21s
INFO: 1733 processes: 1733 local.
FAILED: Build did NOT complete successfully
```
Let me know if you need any additional info.

**Comment by Tombana** [comment] 2020-06-25 22:17
Thanks for raising this issue! I will try to reproduce this.

By the way, our build docs need some updating, because by default the docker container will have `python` pointing to python 2, and that means bazel will build the pip package for python 2 as well, and you likely want to build it for python 3. This could be done by symlinking `python` to `python3.x` and then running `bazel clean --expunge`.

While I try to reproduce the error, if you want to try then you can run bazel outside of the docker container. In that case,
- first run `./configure.sh` and answer `no`
- make sure you're in a python environment that matches the python version you want to build the pip package for (either the system environment or a virtual environment)
- to make bazel re-detect the python version, a full clean is required: `bazel clean --expunge`

**Comment by lkindrat-xmos** [comment] 2020-06-26 12:26
Thanks Tom, the build was successful outside the container.

**Comment by Tombana** [comment] 2020-06-26 12:30
Glad to hear that.
I reproduced the problem locally, I'm not sure what the cause is. Our CI builds use the same docker container and don't crash. However they are running the following script for each build, in order to set the python versions: https://github.com/larq/compute-engine/blob/master/.github/tools/release_linux.sh  I expect that somewhere in one of the `apt-get install` commands, some package is updated that fixes the bug.

When we update our build docs, I'll make sure to verify that all the instructions on the website are working as expected.

**Comment by lgeiger** [comment] 2020-08-28 20:24
Closed via https://github.com/larq/docs/pull/124

**Closed by lgeiger** 2020-08-28 20:24 UTC
