### ISSUE TITLE
Failed to resolve: org.larq:lce-lite:0.4.0

### ISSUE THREAD

**Issue by tehtea** [larq/compute-engine#602] opened 2021-02-08 18:14 UTC
### Describe the bug
After doing a Gradle sync on the Tflite Android Image Classification example application, Android Studio throws this warning and the app cannot be built.

### To Reproduce
Follow the steps [here](https://docs.larq.dev/compute-engine/quickstart_android/), namely:
1. Add the below to the app-level build.gradle:
```gradle
allprojects {
    repositories {
        maven {
            url  "https://dl.bintray.com/plumeraihq/larq-compute-engine"
        }
    }
}
```
2. Add the below to the `lib_support` build.gradle:
```gradle
dependencies {
    ...
    implementation 'org.larq:lce-lite:0.4.0'
    ...
}
```

### Expected behavior
Should be able to sync with gradle without any issues.

### Environment
Windows 10, Gradle 4.0.0, Android Studio 4.1.2, 

TensorFlow version: NIL
Larq version: 0.4.0

I suspect this is caused by how the [nested maven metadata file](https://dl.bintray.com/plumeraihq/larq-compute-engine/org/larq/lce-lite/:maven-metadata.xml) does not declare the latest version as 0.4.0 because this problem goes away when I replace `implementation 'org.larq:lce-lite:0.4.0'` with `implementation 'org.larq:lce-lite:0.1.2'` instead

**Comment by tehtea** [comment] 2021-02-09 14:05
No worries, thanks for this awesome library too!

I don't have the maven CLI installed but it worked locally on the Tensorflow-lite Image Classification example app with the following changes:
1. Downloaded the latest `.aar` from the link you placed, and placed it in `./android\lib_support\libs` 
2. Do the following to `lib_support/build.gradle`:

```groovy
Remove: 
    implementation fileTree(dir: 'libs', include: ['*.jar'])
Replace with: 
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])

Remove: 
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'

Remove: 
    implementation 'org.tensorflow:tensorflow-lite-support:0.1.0'
Replace with:     
    implementation ('org.tensorflow:tensorflow-lite-support:0.1.0') {
        exclude module: 'tensorflow-lite'
    }
```

**Comment by Tombana** [comment] 2021-02-09 15:13
Thank you very much for figuring that out. If it's ok with you, then we'll copy this information into our docs for future users. (Then we can remove the maven-related things from the docs).

**Comment by tehtea** [comment] 2021-02-09 15:15
Yeah for sure, feel free to do so!

**Comment by LJHG** [comment] 2021-04-27 15:48
Hi, I am also trying to go through the turorial [here](https://docs.larq.dev/compute-engine/quickstart_android/) about builing an Android App. And I tried the method of @tehtea, but I guess it does not work for me though.
## about the bug
I succeed to build on Android Studio, but fail to run, and it reports like this at the running stage:
```
E/tensorflow: ClassifierActivity: Failed to create classifier.
    java.lang.IllegalArgumentException: Failed to load XNNPACK delegate from current runtime. Have you added the necessary dependencies?
```

```
E/tensorflow: CameraActivity: Exception!
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.setPixels(int[], int, int, int, int, int, int)' on a null object reference
```

## reproduce
And here's what I did all the way:
1. download the examples from [here](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification).
2. Go to Build > Select Build Variant and select  **supportDebug** for **TFLite_Image_Classification_Demo_App.app** and otheres for **debug** to use the solution of **lib_support** instead of **lib_task_api**.
3. Download the aar file [here](https://github.com/larq/compute-engine/actions/runs/522141342), and excute the command 
to install it in my local maven.
  ```
  mvn install:install-file \
      -Dfile=lce-lite-v0.5.0.aar \
      -DgroupId=org.larq \
      -DartifactId=lce-lite -Dversion=0.1.000 -Dpackaging=aar
  ```
4. add **mavenLocal()** in the **build.gradle** file under Android folder, and it looks like this.
```
allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
    }
}
```
5. Follow the steps mentioned by @tehtea to modify **build.gradle** under lib_supoort folder , However, I use localMaven for the lce.
and it finally looks like this
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(":models")
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'org.larq:lce-lite:0.1.000' 

    // Build off of nightly TensorFlow Lite
    //implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
    implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly-SNAPSHOT'


    //implementation 'org.tensorflow:tensorflow-lite-support:0.1.0'
    implementation ('org.tensorflow:tensorflow-lite-support:0.1.0') {
        exclude module: 'tensorflow-lite'
    }
    // Use local TensorFlow library
    // implementation 'org.tensorflow:tensorflow-lite-local:0.0.0'
}
```
6. Build and run.

PS: The app may quite unexpectedly when running on real device.


I'm new to Android, so if there's anything that written ambiguous, feel free to reply!
Any help would be appreciated!
Thanks!

**Comment by CNugteren** [comment] 2021-07-06 12:47
We have just updated our [documentation](https://docs.larq.dev/compute-engine/quickstart_android/) thanks to your input, see [here](https://github.com/larq/docs/pull/280) for details.

I think all the issues reported here are now resolved, so I'm closing this. Feel free to re-open if you think otherwise - or open a new issue if you have encountered any other problems with LCE on Android.

**Closed by CNugteren** 2021-07-06 12:47 UTC
